import Head from "next/head";
import { useRouter } from "next/router";
import Counter from "../components/Counter";






export default function Home() {
  const router = useRouter()
  return (
    <div>
      <Head>
        <title>Bootstrap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="d-flex flex-column justify-content-center align-items-center vh-100 " style={{backgroundColor:'purple'}}>
        <Counter/>
        <button className="btn btn-primary mt-2" onClick={()=>router.push('/users')}>Go to Redux Saga Example users</button>      
        <button className="btn btn-primary mt-2" onClick={()=>router.push('/dogs')}>Go to Redux Saga Example dogs</button>      
        <button className="btn btn-primary mt-2" onClick={()=>router.push('/datagrid')}>Go to React Table Example </button>      

      </main>
    </div>
  );
}
